# basic Travis script to run ANTLR CI tests for OpenQASM
language: python
python: 3.7
install: "pip install -r requirements.txt"
before_script: antlr4 -Dlanguage=Python3 source/grammar/qasm3.g4
script: pytest
