name: 🚀 Feature request
description: Suggest an idea for this project 💡!
title: '[]:'
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: What is the expected behavior?
    validations:
      required: true
