---
encoding: utf8
default_branch: main
collapse_pre_releases: true
branch_name_prefix: stable/
branch_name_re: stable/.+
release_tag_re: (ast-py\/(?:v?[\d.ab]|rc)+)  # digits, a, b, and rc cover regular and pre-releases
