name: Publish Live Version

on:
  push:
    branches: [ mbh-versioning ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML
        run: ./buildPublishable.sh mbh-versioning

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GHPAGES_DEPLOY_TOKEN }}
          repository-name: mbhealy/mbhealy.github.io
          branch: mbh-versioning
          folder: publish_build/
