name: Publish Stable Version

on:
  push:
    branches: [ 'stable/**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML
        run: VERSION=${GITHUB_REF##*/} make html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GHPAGES_DEPLOY_TOKEN }}
          repository-name: mbhealy/mbhealy.github.io
          branch: mbh-versioning
          folder: build/html
          target-folder: versions/${GITHUB_REF##*/}

      - name: Generate version index files
        working-directory: ./source/versionIndex
        run: make html

      - name: Deploy 🚀 version index to root
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.GHPAGES_DEPLOY_TOKEN }}
          repository-name: mbhealy/mbhealy.github.io
          branch: mbh-versioning
          folder: ./source/versionIndex/_build/html
